export const types = {
  GET_CURRENT_WEATHER_SUCCESS: "GET_CURRENT_WEATHER_SUCCESS",
  GET_CURRENT_WEATHER_LOADING: "GET_CURRENT_WEATHER_LOADING",
  GET_CURRENT_WEATHER_ERROR: "GET_CURRENT_WEATHER_ERROR",
  GET_FORECAST_SUCCESS: "GET_FORECAST_SUCCESS",
  GET_FORECAST_LOADING: "GET_FORECAST_LOADING",
  GET_FORECAST_ERROR: "GET_FORECAST_ERROR",
};
