import React from "react";
import {
  WiDaySunny,
  WiSnow,
  WiNightSnow,
  WiRainWind,
  WiSnowflakeCold,
  WiNightAltCloudyHigh,
  WiDayLightWind,
  WiThermometer,
  WiDayCloudyHigh,
  WiDayHaze,
  WiCloud,
  WiCloudy,
  WiFog,
  WiCloudyWindy,
  WiShowers,
  WiNightAltRain,
  WiNightCloudy,
  WiDayShowers,
  WiNightClear,
  WiDaySleetStorm,
  WiDayStormShowers,
  WiRainMix,
  WiNightAltShowers,
  WiDayCloudyWindy,
  WiNightAltSleetStorm,
  WiSleet,
} from "react-icons/wi";

const ImageIcons = ({ size, color, number }) => {
  let Icons = {
    1: <WiDaySunny size={size} color={color} />,
    2: <WiDayLightWind size={size} color={color} />,
    3: <WiDayLightWind size={size} color={color} />,
    4: <WiDayCloudyHigh size={size} color={color} />,
    5: <WiDayHaze size={size} color={color} />,
    6: <WiDayHaze size={size} color={color} />,
    7: <WiCloud size={size} color={color} />,
    8: <WiCloudy size={size} color={color} />,
    11: <WiFog size={size} color={color} />,
    12: <WiShowers size={size} color={color} />,
    13: <WiDayShowers size={size} color={color} />,
    14: <WiDayShowers size={size} color={color} />,
    15: <WiDaySleetStorm size={size} color={color} />,
    16: <WiDaySleetStorm size={size} color={color} />,
    17: <WiDayStormShowers size={size} color={color} />,
    18: <WiRainMix size={size} color={color} />,
    19: <WiCloudy size={size} color={color} />,
    20: <WiDayCloudyWindy size={size} color={color} />,
    21: <WiDayCloudyWindy size={size} color={color} />,
    22: <WiSnow size={size} color={color} />,
    23: <WiSnow size={size} color={color} />,
    24: <WiSnowflakeCold size={size} color={color} />,
    25: <WiSleet size={size} color={color} />,
    26: <WiRainWind size={size} color={color} />,
    29: <WiRainWind size={size} color={color} />,
    30: <WiThermometer size={size} color="#f24545" />,
    31: <WiThermometer size={size} color="#459cf2" />,
    32: <WiCloudyWindy size={size} color={color} />,
    33: <WiNightClear size={size} color={color} />,
    34: <WiNightClear size={size} color={color} />,
    35: <WiNightCloudy size={size} color={color} />,
    36: <WiNightCloudy size={size} color={color} />,
    37: <WiCloudy size={size} color={color} />,
    38: <WiCloudy size={size} color={color} />,
    39: <WiNightAltShowers size={size} color={color} />,
    40: <WiNightAltShowers size={size} color={color} />,
    41: <WiNightAltRain size={size} color={color} />,
    42: <WiNightAltSleetStorm size={size} color={color} />,
    43: <WiNightAltCloudyHigh size={size} color={color} />,
    44: <WiNightSnow size={size} color={color} />,
  };
  return Icons[number];
};

export default ImageIcons;
